### ISSUE TITLE
json output not reliable

### ISSUE THREAD

**Issue by smeulend** [eNeRGy164/LivingDocumentation#25]
The generated output file does not always result in the same json file. It seems certain type descriptions are missing. 
In case  something is wrong it is better to let it fail rather than continuing with incomplete data.

**Comment by eNeRGy164** [comment]
Hi,
Thanks for reporting this.
If you can provide any form of (reproducible) example, it would help me investigating this.

**Comment by SierraNL** [comment]
Looking a little into this issue, could the caused be the buildalyzer library? 
Since they are having an issue related to missing output (on Linux):
daveaglick/Buildalyzer#134

**Comment by eNeRGy164** [comment]
This looks promising indeed, also: https://github.com/daveaglick/Buildalyzer/issues/138

**Comment by daveaglick** [comment]
Buildalyzer 3.0.1 is now rolling out to NuGet and should (hopefully) resolve this issue. If you get a chance to try it out, please let me know if it resolves the problem.

**Comment by eNeRGy164** [comment]
@daveaglick After having it in a build pipeline on Linux for a couple of weeks, I conclude the issues are fixed.
