### ISSUE TITLE
Move build pipeline to GitHub actions

### ISSUE THREAD

**Issue by eNeRGy164** [eNeRGy164/LivingDocumentation#30]
- [x] Use GitHub actions for build & test
- [x] Have private previews for pull requests
- [ ] Have main builds publish to NuGet
- [ ] Make publishing to GitHub a manual step or require approval

**Comment by Meir017** [comment]
I did something similar for publishing to NuGet, 
in https://github.com/fluentassertions/fluentassertions.analyzers/blob/main/.github/workflows/release.yml I have a trigger based on new git tags, then when I'm ready I just push a new tag and created a new release (use the GitHub generated docs and manually modify if needed)

**Comment by eNeRGy164** [comment]
Thanks for your respons. I implemented this in the successor of this project, and it works in a similar way.

**Comment by Meir017** [comment]
@eNeRGy164 so is this project no longer being actively worked on? in which repository did you make these changes?

**Comment by eNeRGy164** [comment]
The code is moved to https://github.com/dendrodocs/dotnet-tool / https://github.com/dendrodocs/dotnet-shared-lib.
This is a rebrand and restructure of the existing code. It is also extended with a Java version that uses the same JSON schema.

I will put an announcement on this repo when that transition is more finished. Still waiting for a logo design, etc. 😄
