### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException: 

### ISSUE THREAD

**Issue by SirBillofLane** [eNeRGy164/LivingDocumentation#57]
LivingDocumentation.Descriptions, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' is not compatible with 'ConsoleApp1.Statement, ConsoleApp1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Path '[0].Constructors[0].Statements[0].$type', line 1, position 524.'
[analysis.txt](https://github.com/eNeRGy164/LivingDocumentation/files/12224893/analysis.txt)

**Comment by eNeRGy164** [comment]
Did you add the `LivingDocumentation.Json` NuGet package to your project?

This provides the method `JsonDefaults.DeserializerSettings()` that will create a serializer with all requirements to work with the generated file.

See https://github.com/eNeRGy164/LivingDocumentation.Workshop/blob/f448702f347d3d5044fbc6adc698553b19051bd0/2.living-documentation/solutions/22.PitstopDocumentationRenderer/PitstopDocumentationRenderer/Program.cs#L18C88-L18C123 as an example.
