### ISSUE TITLE
Deserialization Issue: Could not load assembly 'LivingDocumentation.Statements'

### ISSUE THREAD

**Issue by asmorger** [eNeRGy164/LivingDocumentation#59]
I am attempting to work `Living Documentation` into my `Nuke.build` CI pipeline, but I'm getting stuck pretty quickly.  I am able to generate the analysis file, but the deserialization of it fails.

- As far as I can tell, I am referencing the right packages.  
- `LivingDocumentation.Statements` is identified as a transitive dependency by default
- Adding this as a direct dependency does not resolve the issue
- I have confirmed that everything is `net7.0` all the way down

### Nuget references from my Nuke csproj:
```xml
  <ItemGroup>
    <PackageReference Include="LivingDocumentation.Json" Version="0.4.0" />
    <PackageReference Include="LivingDocumentation.RenderExtensions" Version="0.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageDownload Include="LivingDocumentation.Analyzer" Version="[0.4.0]" />
  </ItemGroup>
```

### Nuke setup:
```csharp
    [NuGetPackage(
        packageId: "LivingDocumentation.Analyzer",
        packageExecutable: "LivingDocumentation.Analyzer.dll",
        Framework = "net7.0")]
    readonly Tool Documentation;

    Target Document => _ => _
        .Executes(() =>
        {
            Documentation($"--solution {Solution.Path} --output {Paths.Artifacts.LivingDocumentation}");

            string fileContent = File.ReadAllText(Paths.Artifacts.LivingDocumentation);
            var types = JsonConvert.DeserializeObject<List<TypeDescription>>(fileContent,  JsonDefaults.DeserializerSettings());
        });

```

### Execution summary
```bash
07:43:38 [INF] > /usr/bin/dotnet /home/user/.nuget/packages/livingdocumentation.analyzer/0.4.0/tools/net7.0/any/LivingDocumentation.Analyzer.dll --solution /home/user/dev/work/project/src/api/Bespoke.sln --output /home/user/dev/work/project/.artifacts/analysis.json
07:43:43 [DBG] Living Documentation Analysis output generated in 5313ms at /home/user/dev/work/project/.artifacts/analysis.json
07:43:43 [ERR] Target Document has thrown an exception
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'LivingDocumentation.If, LivingDocumentation.Statements'. Path '[1].Methods[0].Statements[4].$type', line 1, position 4124.
 ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'LivingDocumentation.Statements'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
...
```

Any ideas what I'm doing wrong?

**Comment by asmorger** [comment]
Ok, I know what is happening.

As part of my solution, I normally add a folder where I link out to useful things that may or may not be dotnet related, like this:
![image](https://github.com/eNeRGy164/LivingDocumentation/assets/1767853/56326e22-fa38-4f36-8f10-394c2a50c3cc)

One of those things I reference is my `Nuke` project for easy reference and less context switching.  Except in this case I'm now adding a project reference that contains references to the `LivingDocumentation` dependencies themselves, which appears to be the source of my problems.  These assemblies are now types that are appearing in the `analysis.json`.

If I remove the solution reference to the `_build` project, everything works as intended.

While I'm evaluating `LivingDocumentation` this is a fine compromise, but I would hate to lose the ability to reference that project long term.  I may look into adding an `ExcludeProject` flag to the Analyzer so we can add a path forward for supporting this scenario.  A quick glance at the project seems like it would be easy enough, assuming you're open to PRs :+1:

**Comment by eNeRGy164** [comment]
Hey asmorger,

Firstly, I must apologize for not recognizing this behavior earlier. It's a bit ironic (and admittedly a tad silly) that LivingDocumentation struggles with LivingDocumentation-based applications. I've faced this very issue myself before.

Your idea of introducing an `ExcludeProject` flag sounds great. Supporting (multiple) exclusions would indeed be a valuable enhancement. I wholeheartedly welcome contributions. Up until now, the project's direction has been primarily driven by my own needs, but I believe community contributions like yours can truly enrich it.

Looking forward to seeing your issue/PR! 😊

**Comment by eNeRGy164** [comment]
Implemented 🎉
