### ISSUE TITLE
StringBuilder Extensions are missing

### ISSUE THREAD

**Issue by marchinm** [eNeRGy164/LivingDocumentation#71]
While trying to compile the PitstopDocumentationRenderer (solution 25.PitstopDocumentationRenderer), I found it was referencing StringBuilder extension methods (e.g., Deactivate, AltStart, etc.) that aren't available in LivingDocumentation.RenderExtensions. Is the code for the extension methods available?

**Comment by eNeRGy164** [comment]
I'm sorry that the sample code is not working.

I think the methods have moved to the https://github.com/eNeRGy164/PlantUml.Builder project, available as a separate NuGet package.

**Comment by marchinm** [comment]
Thanks! This seems to have the missing parts.
